# Generated by Django 2.2.3 on 2019-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='count',
            new_name='max_player',
        ),
        migrations.RemoveField(
            model_name='park',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='park',
            name='long',
        ),
        migrations.AddField(
            model_name='park',
            name='image_url',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
    ]
