# Generated by Django 2.2.3 on 2019-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190919_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='profile',
            field=models.ManyToManyField(to='main_app.Profile'),
        ),
    ]
