# Generated by Django 2.2.3 on 2019-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190919_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(to='main_app.Game'),
        ),
    ]
